# Makefile

# postgres in docker
export DB_HOST := 172.17.0.2
export DB_USER := postgres
export DB_PASSWORD := 12345
export DB_BANCO := codenation
export DB_PORT := 5432

export JWT_SECRET = SecretJWTKeyCodeNation

run:
	go run main.go